# Generated by Django 3.1.1 on 2020-09-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('short_details', models.CharField(max_length=250)),
                ('world_rank', models.IntegerField()),
                ('image', models.ImageField(upload_to='university')),
                ('tags', models.ManyToManyField(null=True, to='home.UniversityTag')),
            ],
        ),
    ]
