# Generated by Django 3.1.1 on 2020-09-27 17:00

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=smartfields.fields.ImageField(upload_to='university'),
        ),
    ]
