# Generated by Django 3.1.1 on 2020-10-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200927_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='short_details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='u_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='universitytag',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
